stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw
    #params:
    #  - data_ingestion.batch_size
    #  - data_ingestion.shuffle
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw
    outs:
      - data/interim
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/interim
    outs:
      - data/processed
  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/processed
    outs:
      - models/model.pkl
  model_evaluation: 
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/model.pkl
      - data/processed
    outs:
      - reports/evaluation_report.txt
  
  